###ALIASES###

#Python
alias venv='pyvenv-3.4'
alias cheat='python3 ~/.cheat.d/cheat.py'
alias p2='python2.7'
alias p3='python3'
alias p3.5='python3.5'

#Emacs
alias ec='emacsclient'
alias ect='emacsclient -t'
alias ecc='emacsclient -c'

#tmux
alias tmux='tmux -2'

#Other
alias sshuni='~/CloudStation/Studium/SSHUniNetz.sh'
alias atom_packages='apm list --installed --bare | grep '^[^@]\+' -o'
alias nautilus='nautilus --no-desktop'

#i3
alias i3lock='i3lock --color=19353D'
