###ALIASES###

#Python
alias venv='pyvenv-3.4'
alias cheat='python3 ~/.cheat.d/cheat.py'

#Emacs
alias ec='emacsclient'
alias ect='emacsclient -t'
alias ecc='emacsclient -c'

#tmux
alias tmux='tmux -2'

#Other
alias sshuni='~/CloudStation/Studium/SSHUniNetz.sh'
alias atom_packages='apm list --installed --bare | grep '^[^@]\+' -o'

#i3
alias i3lock='i3lock --color=19353D'
